import type { Metadata } from "next";

import "./globals.css";
import LayoutGeneral from "@/components/LayoutGeneral";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LayoutGeneral>{children}</LayoutGeneral>
      </body>
    </html>
  );
}
